#!/bin/sh

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
	echo "Missing target directory"
	exit 1
fi

# user to give access to. can be hardcoded or fetched from some other place
: ${USER:="myuser"}
# keytype: rsa or dsa
: ${KEYTYPE:="rsa"}

USERHOME="$(eval echo ~$USER)"

if [ -f $USERHOME/.ssh/id_$KEYTYPE.pub ]; then
	install -D -m 0700 -o root -g root \
		$USERHOME/.ssh/id_$KEYTYPE.pub $TARGET/root/.ssh/authorized_keys
fi

exit 0
